### ISSUE TITLE
how to initialize a VSS character iterator

### ISSUE THREAD

**Issue by Richard-52** [AdaCore/VSS#134]
I have set myself a project to develop an Ada target for Antlr4.
The input character stream for the target lexer must be able to process a series of input files loaded one after the other. For each input file the processing is pretty simple:
```
load a data file into a virtual string
set an iterator to the first character
loop
   return the next character as requested by the lexer
end loop
```
I need to use the same virtual string and and iterator variables for each file processed but I can't do this because the iterator is a 'limited' type and can only be initialised once when it is declared.
There is probably a way around this but going through the code I can't find a function that helps me or any other way to do this and I would prefer not to do my own modification of the VSS code to implement what I need.
Any help would be appreciated.

**Comment by godunko** [comment]
Hello,

Can you please explain your algorithm?

Iterators in VSS is intended to be used only to run loops and can't be stored. If you need to remember location you can take marker from the iterator. It is possible to reconstruct iterator from the marker. However, note, all markers and iterators are invalidated when value of corresponding string object are modified by assignment of another string object, as well as may be invalidated on modification of corresponding string object (position may be modified otherwise if iterators supports this).

**Comment by Richard-52** [comment]
Vadim,

Thank you for responding.

Since VSS is evolving and there is not much documentation to support it yet I have spent a long time working through the source code. I think I understand most of it including the concepts and use of cursors, markers and iterators as you mentioned.

I want to use a Virtual_String as the stream of characters to be processed by a lexical analyser (lexer). The lexer works along the string reading and processing one character at a time. The processing can be quite complex and sometimes the lexer will inspect characters forward or backward from the current character position. The lexer might inspect characters more than 1 character forward or backward from the current position. Once the lexer has inspected the characters it needs to it will adjust the current position to one of the inspected characters.

Most lexers use simple numerical indexing to reference the input characters and the main 3 methods they seem to use are:

1. LA(n), which returns the character n characters forward (n > 0) or backward (n < 0) from the current position.
2. Consume, which moves the current position forward 1 character, and
3. Seek(index), which sets the current position to the character position specified by index.

If I load an entire file into a Virtual_String and then convert it to a Wide_Wide_String I can implement and use these index-based methods easily. However some input files can be very large and use a lot of memory. Since I want to learn to use VSS and it doesn't appear to offer direct indexing thought I might be able implement these functions with cursors, markers and iterators and reduce memory use by not using a Wide_Wide_String.

I was exploring this idea when I discovered that an iterator can only be initialised at the time of declaration because it is a limited type. The lexer was going to have one Virtual_String variable and one character iterator that would be re-used for each data file processed.

I hope this explains clearly enough what I am trying to do.

**Comment by godunko** [comment]
Thank you for explanation!

I'm against of changing of iterator from limited type to non-limited types, however, it is possible to add procedures to initialize existing iterator object to iterate over some string object. For example, add subprogram like


```
package VSS.Strings.Cursors.Interators.Characters is

  procedure Set_To_First_Character
    (Self : in out Character_Iterator;
     On   : in out Virtual_String);

```  

Is it works for you?

**Comment by Richard-52** [comment]
Yes, a subprogram like that will work for me.

I am also against changing the iterator to a non-limited type. Because the iterator is a limited type and VSS doesn't already have a subprogram like the one you suggest adding, I felt I am trying to use VSS in a way that it wasn't intended to be used.

Even if I add the new subprogram, implementing the LA(n) subprogram using cursors, markers and iterators is also not going to be ideal.

Overall I think using VSS by itself is probably not a good fit for this type of application. I think it might be better to use a Virtual_String as the input stream to convert UTF-8 encoded files to UTF-32 characters which are then inserted as needed into into a small sliding buffer. The LA(n), consume and seek(index) subprograms can then be implemented using indexing to operate on this small buffer and new characters can be obtained from the Virtual_String as they are needed.

As a learning exercise I might try using VSS by itself and also with a small sliding buffer.

**Comment by godunko** [comment]
VSS doesn't have such subprograms only because nobody requested them :)

The only issue you may have with VSS vs. Wide_Wide_String is performance. VSS takes more time retrieve character under the cursor, and to move iterator forward/backward. It is hard to guess is it visible to overall performance of the application or not.

So, I've added Set_At_First/Set_At_Last subprograms to character iterator, and also Set_Before_First/Set_After_Last subprograms, which may be useful to produce smaller and cleaner code in some cases.

PS. If you have iterator and what to create another one, it is sufficient to use Virtual_String.Character subprogram to create new iterator from another iterator without conversion to/from markers.

**Comment by Richard-52** [comment]
Vadim,

Thank you for your help.

Performance is not an issue for me at the moment. Among other things the application also needs to access slices of the UTF_32 and UTF_8 versions of the string at the same time. I am hoping that the features of VSS will save me having to write more code than I need to.

Richard Sellar
Director
Syniad Pty Ltd
(m) 0418 890 738
***@***.***
